import { IData } from "../types/Data";

const testData: IData[] = [
  {
    array_of_ords: 777,
    discord_link: 'discord.gg/project1',
    discord_users: 1000,
    floor: 5,
    ico: 'https://via.placeholder.com/150',
    id: 1,
    name: 'Project-1',
    ords_level_high: 10,
    ords_level_low: 0,
    supply: 2000,
    twitter: '@project1',
    website: 'www.project1.com',
  },
  {
    array_of_ords: 777,
    discord_link: 'discord.gg/project2',
    discord_users: 1500,
    floor: 10,
    ico: 'https://via.placeholder.com/150',
    id: 2,
    name: 'Project-2',
    ords_level_high: 15,
    ords_level_low: 0,
    supply: 2500,
    twitter: '@project2',
    website: 'www.project2.com',
  },
  {
    array_of_ords: 777,
    discord_link: 'discord.gg/project3',
    discord_users: 2000,
    floor: 15,
    ico: 'https://via.placeholder.com/150',
    id: 3,
    name: 'Project-3',
    ords_level_high: 20,
    ords_level_low: 0,
    supply: 3000,
    twitter: '@project3',
    website: 'www.project3.com',
  },
  {
    array_of_ords: 777,
    discord_link: 'discord.gg/project4',
    discord_users: 2500,
    floor: 20,
    ico: 'https://via.placeholder.com/150',
    id: 4,
    name: 'Project-4',
    ords_level_high: 25,
    ords_level_low: 0,
    supply: 3500,
    twitter: '@project4',
    website: 'www.project4.com',
  },
  {
    array_of_ords: 777,
    discord_link: 'discord.gg/project5',
    discord_users: 3000,
    floor: 25,
    ico: 'https://via.placeholder.com/150',
    id: 5,
    name: 'Project-5',
    ords_level_high: 30,
    ords_level_low: 0,
    supply: 4000,
    twitter: '@project5',
    website: 'www.project5.com',
  },
];

export default testData
